backend:
    name: github
    branch: master
    repo: bgoonz/BGOONZ_BLOG_2.0
    open_authoring: true
backend:
  name: git-gateway

local_backend:
  # when using a custom proxy server port
  url: http://localhost:8082/api/v1
  # when accessing the local site from a host other than 'localhost' or '127.0.0.1'
  allowed_hosts: ['192.168.0.1']    
---
media_folder: static/uploads
public_folder: /static/uploads
publish_mode: editorial_workflow
collections:
